[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

monitor_speed = 115200

lib_deps =
    https://github.com/KSJain/KSJ_Display.git#v0.1.0-Initial-public-release
    https://github.com/KSJain/KSJ_Input.git#v0.1.0